### PR TITLE
migrate project to gradle 7.1.1

### PR DESCRIPTION
**Pull request by stafanluedtke**
This pull request should fix the bug #26. It removes outdated plugins like the apt plugin and the repository jcentral.

### CODE REVIEW

**Comment by Tavo5691** [comment]
@muhlba91 Can you review this PR, please? 

It would be awesome having Gradle 7.x support.

**Comment by muhlba91** [comment]
thanks for the ping! i‘ll check it in the next couple of days - trying to get it done by tomorrow/wednesday.

**Review by muhlba91 — CHANGES_REQUESTED** [review]
i think your (auto-)formatting uses tab characters for indents; the files in this project use 4 space characters. it also gets rather difficult spotting the actual changes you made.
could you please keep the consistency by reverting your indent changes?

otherwise, good to go from my side - once consistency is there, i'll have a quick look again and will merge your PR. :+1:

**Comment by muhlba91** [comment]
@Tavo5691 @stafanluedtke merged and released as version `2.0.0`.

**Pull request merged**
